# Generated by Django 4.2.30 on 2026-08-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationreminder',
            name='notification_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=5),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='reminder_time',
            field=models.TimeField(),
        ),
    ]
